#!/bin/bash

echo
echo "Attempting to mount..."
echo

mount /dev/sda2 /mnt/gentoo
mount /dev/sda1 /mnt/gentoo/efi
mount --types proc /proc /mnt/gentoo/proc
mount --rbind /sys /mnt/gentoo/sys
mount --make-rslave /mnt/gentoo/sys
mount --rbind /dev /mnt/gentoo/dev
mount --make-rslave /mnt/gentoo/dev
mount --bind /run /mnt/gentoo/run
mount --make-slave /mnt/gentoo/run
mount --types tmpfs --options nosuid,nodev,noexec shm /dev/shm
#chroot /mnt/gentoo /bin/bash

echo "!~~~mounting finished~~~!"
